name: Build and test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Generate code coverage
        run: ./gradlew app:koverXmlReportDebug
      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: app/build/coverage-report/result.xml